### ISSUE TITLE
Cost-basis option home

### ISSUE THREAD

**Issue by hmcgrath** [NRCan/CanCurve#23]
I know I was a real pain about this Cost Basis living on Data Input. and I like it there, but, could it also exist  on the Create Curve tab as well? and have the variable update as the user changes on one tab or the other? 

![image](https://github.com/user-attachments/assets/bf33fe56-06ab-40b9-aab7-8d257b15d0a4)

**Comment by cefect** [comment]
Yes, this is possible. But I think having the setting in two place (and changing while hidden from the user) risks confusing people. And I'm not sure what the advantage is. I would vote to move it back to 'Create Curve'

**Comment by cefect** [comment]
Moved to 'Create Curve' tab per discussion 
![image](https://github.com/user-attachments/assets/117940f0-13a9-49c2-8cc6-5bf3868d9724)
