### ISSUE TITLE
Function/Role of Exposure Units by DRF? 

### ISSUE THREAD

**Issue by hmcgrath** [NRCan/CanCurve#24]
On the Data Input tab, beside the Depth Replacement-Factor Database, there is a _Exposure Units_ option. 
-I'm not clear on the purpose of this? 
it doesn't seem to perform a conversion. Is it just for the user to specify the overall units of the DRF database?  If so,  wondering how we could better label it or if there is a setting in the DRF database that could be read and auto-apply the units. 
![image](https://github.com/user-attachments/assets/699a34cf-4281-4621-96bc-7fc74a22f9f6)

**Comment by cefect** [comment]
This provides the unit for the columns in the DRF

![image](https://github.com/user-attachments/assets/1696a162-7fc6-429c-a407-f798159e1e06)

It would probably better if this was read directly from the database (then displayed here for the user). But this would need an additional table to be included in the MRB.

**Comment by cefect** [comment]
improvements to the handling of units have been added to the dev branch. Also added some discussion in the [documentation](https://github.com/NRCan/CanCurve/commit/415248f5c1820fd743410aecbc6abe0577e7970b).
